---
- name: webserver installation (with documentation)
  hosts: webserver
  remote_user: root
  vars:
    disable_default: true

  tasks:
    - name: apache & php installation
      apt:
        pkg:
          - apache2
          - php

    - name: add user
      user:
        name: "{{ user  }}"
        password: !
        shell: /bin/false

    - name: document root exist
      file:
        path: "/var/www/{{ domain }}"
        state: directory
        owner: "{{ user }}"
        mode: '0755'

    - name: custom index.html
      copy:
        dest: "/var/www/{{ domain }}/index.html"
        content: |
                    Custom Web Page

    - name: set up Apache virtualhost
      template:
        src: "templates/virtualhost.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"

    - name: enable new site
      command: "/usr/sbin/a2ensite {{ http_conf }}"
      notify: reload Apache

    - name: disable default Apache site
      command: "/usr/sbin/a2dissite 000-default.conf"
      when: disable_default
      notify: reload Apache

    - name: open firewall
      ufw:
        rule: allow
        port: "{{ port }}"
        proto: tcp

  handlers:
    - name: reload Apache
      service:
        name: apache2
        state: reloaded