---
- name: webserver installation (with documentation)
  hosts: webserver
  remote_user: root

  tasks:
    - name: apache & php installation
      apt:
        pkg:
          - apache2
          - php

    - name: add user
      user:
        name: "{{ user  }}"
        password: !
        shell: /bin/false

    - name: create user folder
      file:
        path: /var/www/{{ domain  }}
        state: directory
        owner: "{{ user  }}"
        group: "{{ user  }}"
        mode: 0755

    - name: phpinfo
      copy:
        src: files/index.php
        dest: /var/www/{{ domain  }}
        owner: "{{ user  }}"
        group: "{{ user  }}"
        mode: 0644

    - name: Copy virtualhost
      template:
        src: templates/virtualhost.conf.j2
        dest: /etc/apache2/sites-available/virtualhost.conf

    - name: Remove default virtualhost
      command: a2dissite 000-default.conf
      args:
        removes: /etc/apache2/sites-enabled/000-default.conf
      notify: reload apache

    - name: Add virtaulhost.conf
      command: a2ensite virtualhost.conf
      args:
        creates: /etc/apache2/sites-enabled/virtualhost.conf
      notify: reload apache

  handlers:
    - name: reload apache
      service:
        name: apache2
        state: reloaded



























